services:
  postgres-db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: as1!31%t&j3hk#
      POSTGRES_DB: main
    networks:
      - db

networks:
  db:

volumes:
  postgres-db-data: